"""Render a validated draft as an idempotent SQL script for the Supabase SQL Editor.

Every value goes through the small quoting helpers below; SQL is never built from unvalidated
input. Text is single-quoted with ``'`` doubled (backslashes are literal because the script sets
``standard_conforming_strings = on``), NUL is rejected, numbers are emitted only from validated
``Decimal``/``int`` values, and enum values are checked against the allowed sets. Draft text is
never written into SQL comments.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Sequence
from decimal import Decimal
from typing import Any

from quotes.application.catalog_proposal import VISITOR_CATEGORIES
from quotes.infrastructure.catalog_draft import MAX_PRICE, PRICING_UNITS, ValidatedDraft


class SqlLiteralError(ValueError):
    """A value cannot be written safely as a SQL literal."""


def quote_text(value: str) -> str:
    if not isinstance(value, str):
        raise SqlLiteralError(f"text literal expected, got {type(value).__name__}")
    if "\x00" in value:
        raise SqlLiteralError("text contains a NUL character")
    return "'" + value.replace("'", "''") + "'"


def quote_decimal(value: Decimal) -> str:
    if not isinstance(value, Decimal) or not value.is_finite():
        raise SqlLiteralError("amount must be a finite Decimal")
    if value < 0 or value > MAX_PRICE or value != value.quantize(Decimal("0.01")):
        raise SqlLiteralError("amount must be between 0 and 99999999.99 with at most 2 decimals")
    return f"{value:.2f}"


def quote_int(value: int) -> str:
    if isinstance(value, bool) or not isinstance(value, int) or not 1 <= value < 2**31:
        raise SqlLiteralError("integer must be between 1 and 2147483647")
    return str(value)


def quote_bool(value: bool) -> str:
    if not isinstance(value, bool):
        raise SqlLiteralError("boolean expected")
    return "true" if value else "false"


def quote_enum(value: str, allowed: Sequence[str]) -> str:
    if not isinstance(value, str) or value not in allowed:
        raise SqlLiteralError(f"value must be one of: {', '.join(allowed)}")
    return f"'{value}'"


def _nullable[T](value: T | None, quoter: Callable[[T], str]) -> str:
    return "null" if value is None else quoter(value)


def _upsert(
    table: str,
    columns: Sequence[str],
    rows: Iterable[Sequence[str]],
    conflict: str,
    keys: Sequence[str],
) -> str:
    rows = list(rows)
    if not rows:
        return ""
    values = ",\n".join(f"  ({', '.join(row)})" for row in rows)
    updates = ",\n".join(f"  {c} = excluded.{c}" for c in columns if c not in keys)
    return (
        f"insert into quotes.{table}\n  ({', '.join(columns)})\nvalues\n{values}\n"
        f"on conflict ({conflict}) do update set\n{updates};\n"
    )


_HEADER = """\
-- Generated by `quotes catalog sql` from a reviewed catalog draft.
-- PRIVATE business data: do not commit this file.
-- Paste it into the Supabase SQL Editor and run it once; it is safe to run again (upserts only,
-- no deletes, no DDL). Then run `quotes catalog check` to confirm the catalog loads.
"""

_FOOTER = """\
-- Verification (run after the commit; uncomment to use):
-- select 'pricing_items' as table_name, count(*) from quotes.pricing_items
-- union all select 'local_payment_items', count(*) from quotes.local_payment_items
-- union all select 'local_payment_prices', count(*) from quotes.local_payment_prices;
"""


def _pricing_values(row: dict[str, Any]) -> list[str]:
    return [
        quote_text(row["id"]),
        quote_text(row["category"]),
        quote_text(row["name_es"]),
        quote_text(row["name_en"]),
        quote_enum(row["unit"], PRICING_UNITS),
        quote_decimal(row["price_pen"]),
        _nullable(row["child_price_pen"], quote_decimal),
        _nullable(row["duration_days"], quote_int),
        quote_bool(row["active"]),
        _nullable(row["notes"], quote_text),
    ]


def render_sql(draft: ValidatedDraft) -> str:
    if draft.problems:
        raise SqlLiteralError("refusing to render a draft with problems")
    parts = [
        _upsert(
            "pricing_items",
            (
                "id",
                "category",
                "name_es",
                "name_en",
                "unit",
                "price_pen",
                "child_price_pen",
                "duration_days",
                "active",
                "notes",
            ),
            (_pricing_values(r) for r in draft.item_rows),
            "id",
            ("id",),
        ),
        _upsert(
            "local_payment_items",
            ("id", "name_es", "name_en", "active", "notes"),
            (
                [
                    quote_text(r["id"]),
                    quote_text(r["name_es"]),
                    quote_text(r["name_en"]),
                    quote_bool(r["active"]),
                    _nullable(r["notes"], quote_text),
                ]
                for r in draft.local_rows
            ),
            "id",
            ("id",),
        ),
        _upsert(
            "local_payment_prices",
            ("item_id", "visitor_category", "price_pen"),
            (
                [
                    quote_text(r["item_id"]),
                    quote_enum(r["visitor_category"], VISITOR_CATEGORIES),
                    quote_decimal(r["price_pen"]),
                ]
                for r in draft.price_rows
            ),
            "item_id, visitor_category",
            ("item_id", "visitor_category"),
        ),
    ]
    body = "\n".join(p for p in parts if p)
    return (
        f"{_HEADER}\nbegin;\nset local standard_conforming_strings = on;\n\n{body}\ncommit;\n\n"
        f"{_FOOTER}"
    )
